version: '3'
services:
  web:
    build: ./webapp
    #command: python -u app.py
    ports:
      - "443:5000"
    volumes:
      - ./webapp:/todo
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo:3.0.2
